---
application:
  name: "q-3"
  project: "q3"
  organization: "QoveryCommunity"
  publicly_accessible: true
  dockerfile: backend/Dockerfile
routers:
  - name: "main-q-3"
    custom_domains:
      - branch: main
        domain: api.brocktillotson.tk
    routes:
      - application_name: "q-3"
        paths:
          - "/*"
